/**
 * Enum representing the types of agents in the Mirrorwright Orchestrator
 */
export enum AgentType {
  cline = "cline",
  augment = "augment",
  roo = "roo"
}

/**
 * Interface for agent configuration
 */
export interface AgentConfig {
  /** Agent type */
  type: AgentType;
  
  /** Agent-specific configuration options */
  options?: Record<string, any>;
}

/**
 * Interface for agent input data
 */
export interface AgentInput {
  /** The prompt or instruction for the agent */
  prompt: string;
  
  /** Context data for the agent */
  context?: Record<string, any>;
  
  /** Metadata for the agent */
  metadata?: Record<string, any>;
}

/**
 * Interface for agent output data
 */
export interface AgentOutput {
  /** The content generated by the agent */
  content: string;
  
  /** Metadata from the agent's response */
  metadata?: Record<string, any>;
}

/**
 * Interface for agent adapters
 * Adapters provide a consistent interface for different agent implementations
 */
export interface AgentAdapter {
  /**
   * Initialize the agent adapter
   */
  initialize(): Promise<void>;
  
  /**
   * Send input to the agent and get a response
   * @param input The input data for the agent
   * @returns Promise resolving to the agent's output
   */
  send(input: AgentInput): Promise<AgentOutput>;
  
  /**
   * Shutdown the agent adapter
   */
  shutdown(): Promise<void>;
}
